name: netvfy-agent-ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install tooling
      run: |
        apt-get install build-essential
        apt-get install scons
        apt-get install cmake
        apt-get install libjansson-dev
        apt-get install libevent-dev
        apt-get install libcurl4-openssl-dev
    - name: build netvfy-agent
      run: |
        git submodule init && git submodule update
        cd ./tapcfg
        ./buildall.sh || true
        cd -
        mkdir build_cli && cd build_cli
        cmake .. && make
